name: Git Workout

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Git Workout
    runs-on: ubuntu-latest

    steps:
      - name: Setup Actions
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
        
      - name: Run
        run: |
          go run main.go

      - name: Build
        run: |
          mkdir -p build
          go build -v -o ./build/buildfile main.go